#!/bin/zsh
# setup_claude_glm52_mac.zsh
# macOS zsh-native setup for Claude Code + Zhipu GLM-5.2
# Do not edit this file with Windows Notepad. Keep Unix LF line endings.

set -e
setopt pipefail

echo ""
echo "Claude Code + Zhipu GLM-5.2 setup for macOS"
echo "------------------------------------------------"
echo ""

echo "Choose your Zhipu platform:"
echo "  1) BigModel.cn / 智谱开放平台 China"
echo "     https://open.bigmodel.cn/api/anthropic"
echo ""
echo "  2) Z.AI Global"
echo "     https://api.z.ai/api/anthropic"
echo ""

read "PLATFORM_CHOICE?Select platform [1/2, default 1]: "
PLATFORM_CHOICE="${PLATFORM_CHOICE:-1}"

if [[ "$PLATFORM_CHOICE" == "2" ]]; then
  ANTHROPIC_BASE_URL_VALUE="https://api.z.ai/api/anthropic"
else
  ANTHROPIC_BASE_URL_VALUE="https://open.bigmodel.cn/api/anthropic"
fi

echo ""
read -s "ZHIPU_API_KEY?Enter your Zhipu / Z.AI API key: "
echo ""

if [[ -z "$ZHIPU_API_KEY" ]]; then
  echo "ERROR: API key cannot be empty."
  exit 1
fi

GLM_MAIN_MODEL="glm-5.2[1m]"
GLM_FAST_MODEL="glm-4.5-air"

CLAUDE_DIR="$HOME/.claude"
CLAUDE_SETTINGS="$CLAUDE_DIR/settings.json"
CLAUDE_ROOT_JSON="$HOME/.claude.json"
ZSHRC="$HOME/.zshrc"

mkdir -p "$CLAUDE_DIR"

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

if [[ -f "$CLAUDE_SETTINGS" ]]; then
  cp "$CLAUDE_SETTINGS" "$CLAUDE_SETTINGS.backup.$TIMESTAMP"
  echo "Backup created: $CLAUDE_SETTINGS.backup.$TIMESTAMP"
fi

if [[ -f "$CLAUDE_ROOT_JSON" ]]; then
  cp "$CLAUDE_ROOT_JSON" "$CLAUDE_ROOT_JSON.backup.$TIMESTAMP"
  echo "Backup created: $CLAUDE_ROOT_JSON.backup.$TIMESTAMP"
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 is required but was not found."
  echo "Install it with Homebrew:"
  echo "  brew install python"
  exit 1
fi

export CC_ZHIPU_API_KEY="$ZHIPU_API_KEY"
export CC_ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL_VALUE"
export CC_GLM_MAIN_MODEL="$GLM_MAIN_MODEL"
export CC_GLM_FAST_MODEL="$GLM_FAST_MODEL"
export CC_CLAUDE_SETTINGS="$CLAUDE_SETTINGS"
export CC_CLAUDE_ROOT_JSON="$CLAUDE_ROOT_JSON"
export CC_ZSHRC="$ZSHRC"

python3 <<'PY'
import json
import os
from pathlib import Path

settings_path = Path(os.environ["CC_CLAUDE_SETTINGS"])

if settings_path.exists():
    try:
        data = json.loads(settings_path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            data = {}
    except Exception:
        data = {}
else:
    data = {}

env = data.get("env", {})
if not isinstance(env, dict):
    env = {}

main_model = os.environ["CC_GLM_MAIN_MODEL"]
fast_model = os.environ["CC_GLM_FAST_MODEL"]

env.update({
    "ANTHROPIC_AUTH_TOKEN": os.environ["CC_ZHIPU_API_KEY"],
    "ANTHROPIC_BASE_URL": os.environ["CC_ANTHROPIC_BASE_URL"],
    "ANTHROPIC_MODEL": main_model,
    "ANTHROPIC_DEFAULT_OPUS_MODEL": main_model,
    "ANTHROPIC_DEFAULT_SONNET_MODEL": main_model,
    "ANTHROPIC_DEFAULT_HAIKU_MODEL": fast_model,
    "CLAUDE_CODE_SUBAGENT_MODEL": fast_model,
    "CLAUDE_CODE_EFFORT_LEVEL": "max",
    "API_TIMEOUT_MS": "3000000",
    "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1",
    "CLAUDE_CODE_AUTO_COMPACT_WINDOW": "1000000"
})

data["env"] = env

settings_path.write_text(
    json.dumps(data, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8"
)
PY

python3 <<'PY'
import json
import os
from pathlib import Path

root_path = Path(os.environ["CC_CLAUDE_ROOT_JSON"])

if root_path.exists():
    try:
        data = json.loads(root_path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            data = {}
    except Exception:
        data = {}
else:
    data = {}

data["hasCompletedOnboarding"] = True

root_path.write_text(
    json.dumps(data, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8"
)
PY

python3 <<'PY'
import os
from pathlib import Path

zshrc = Path(os.environ["CC_ZSHRC"])

start = "# >>> Claude Code Zhipu GLM-5.2 env >>>"
end = "# <<< Claude Code Zhipu GLM-5.2 env <<<"

main_model = os.environ["CC_GLM_MAIN_MODEL"]
fast_model = os.environ["CC_GLM_FAST_MODEL"]

block = f"""
{start}
export ANTHROPIC_BASE_URL="{os.environ["CC_ANTHROPIC_BASE_URL"]}"
export ANTHROPIC_AUTH_TOKEN="{os.environ["CC_ZHIPU_API_KEY"]}"
export ANTHROPIC_MODEL="{main_model}"
export ANTHROPIC_DEFAULT_OPUS_MODEL="{main_model}"
export ANTHROPIC_DEFAULT_SONNET_MODEL="{main_model}"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="{fast_model}"
export CLAUDE_CODE_SUBAGENT_MODEL="{fast_model}"
export CLAUDE_CODE_EFFORT_LEVEL="max"
export API_TIMEOUT_MS="3000000"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
export CLAUDE_CODE_AUTO_COMPACT_WINDOW="1000000"
{end}
"""

if zshrc.exists():
    text = zshrc.read_text(encoding="utf-8", errors="ignore")
else:
    text = ""

if start in text and end in text:
    before = text.split(start)[0].rstrip()
    after = text.split(end, 1)[1].lstrip()
    text = before + "\n\n" + block.strip() + "\n\n" + after
else:
    text = text.rstrip() + "\n\n" + block.strip() + "\n"

zshrc.write_text(text, encoding="utf-8")
PY

export ANTHROPIC_BASE_URL="$ANTHROPIC_BASE_URL_VALUE"
export ANTHROPIC_AUTH_TOKEN="$ZHIPU_API_KEY"
export ANTHROPIC_MODEL="$GLM_MAIN_MODEL"
export ANTHROPIC_DEFAULT_OPUS_MODEL="$GLM_MAIN_MODEL"
export ANTHROPIC_DEFAULT_SONNET_MODEL="$GLM_MAIN_MODEL"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="$GLM_FAST_MODEL"
export CLAUDE_CODE_SUBAGENT_MODEL="$GLM_FAST_MODEL"
export CLAUDE_CODE_EFFORT_LEVEL="max"
export API_TIMEOUT_MS="3000000"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
export CLAUDE_CODE_AUTO_COMPACT_WINDOW="1000000"

unset CC_ZHIPU_API_KEY
unset CC_ANTHROPIC_BASE_URL
unset CC_GLM_MAIN_MODEL
unset CC_GLM_FAST_MODEL
unset CC_CLAUDE_SETTINGS
unset CC_CLAUDE_ROOT_JSON
unset CC_ZSHRC

echo ""
echo "Setup complete."
echo ""
echo "Claude settings updated:"
echo "  $CLAUDE_SETTINGS"
echo ""
echo "Claude root config updated:"
echo "  $CLAUDE_ROOT_JSON"
echo ""
echo "zsh profile updated:"
echo "  $ZSHRC"
echo ""
echo "Model mapping:"
echo "  ANTHROPIC_MODEL                -> $GLM_MAIN_MODEL"
echo "  ANTHROPIC_DEFAULT_OPUS_MODEL   -> $GLM_MAIN_MODEL"
echo "  ANTHROPIC_DEFAULT_SONNET_MODEL -> $GLM_MAIN_MODEL"
echo "  ANTHROPIC_DEFAULT_HAIKU_MODEL  -> $GLM_FAST_MODEL"
echo "  CLAUDE_CODE_SUBAGENT_MODEL     -> $GLM_FAST_MODEL"
echo ""
echo "Reload your terminal environment:"
echo "  source ~/.zshrc"
echo ""
echo "Verify:"
echo "  echo \$ANTHROPIC_BASE_URL"
echo "  echo \$ANTHROPIC_MODEL"
echo "  echo \$ANTHROPIC_DEFAULT_HAIKU_MODEL"
echo "  claude --version"
echo "  claude"
echo ""
echo "Security note:"
echo "  Your API key is stored in ~/.claude/settings.json and ~/.zshrc."
echo "  Do not upload these files to GitHub."