// BrandPedia Kids — preset brand library (bilingual zh/en).
// 31 curated brands across 7 categories. Every text field has a parallel *En
// sibling so the generator (lib/contentTemplates.ts) can produce full content
// in either language. The 8 "featured" brands also carry hand-authored prose
// in both languages plus structured dataPoints/timeline.

import type { Brand, Category } from "./types";

export const BRANDS: Brand[] = [
  // ───────────────────────── Food & Drink ─────────────────────────
  {
    id: "coca-cola",
    name: "可口可乐",
    nameEn: "Coca-Cola",
    slug: "coca-cola",
    category: "food-beverage",
    logo: "🥤",
    color: "#E61A27",
    slogan: "开启快乐瞬间",
    sloganEn: "Open Happiness",
    description: "全球最知名的碳酸饮料，把“快乐”装进了红色罐子里。",
    descriptionEn: "The world's most famous soda, bottling happiness in red.",
    featured: true,
    founded: 1886,
    founder: "约翰·彭伯顿",
    founderEn: "John Pemberton",
    country: "美国",
    countryEn: "the United States",
    funFact: "可口可乐最早是药剂师发明的药水，配方至今锁在金库里，全世界只有极少数人知道。",
    funFactEn: "Coca-Cola was first invented as a medicine; the recipe is still locked in a vault.",
    keyFacts: [
      "1886年由药剂师彭伯顿发明，最早当药卖",
      "红色弧形瓶和圣诞老人形象深入人心",
      "全世界每天卖出约19亿瓶",
      "老对手是百事可乐，“可乐大战”持续百年",
    ],
    keyFactsEn: [
      "Invented in 1886 by pharmacist Pemberton, first sold as a medicine",
      "Its red curved bottle and Santa Claus image are world-famous",
      "About 1.9 billion bottles are sold every day",
      "Its old rival is Pepsi — the 'Cola Wars' have lasted a century",
    ],
    story: "1886年，美国药剂师彭伯顿想发明一种能提神的糖浆，他在后院的大铜锅里熬出了可乐的配方。最早它是当药卖的，一杯5美分。后来合伙人给它起了个响亮的名字——可口可乐。今天，这个配方被锁在亚特兰大一个金库里，全世界只有极少数人知道。",
    storyEn:
      "In 1886, American pharmacist John Pemberton wanted to invent an energizing syrup and cooked up the Coke recipe in a copper pot in his backyard. At first it was sold as a medicine, one glass for 5 cents. Later his partner gave it a catchy name — Coca-Cola. Today that recipe is locked in a vault in Atlanta, known to only a few people in the world.",
    product: "可口可乐卖的不只是糖水，而是一种“快乐的感觉”。它甜、有气泡、冰镇后特别爽口，很多人喝它时会想起开心的时刻。它的红色罐子和弧形瓶让人一眼就认出来。",
    productEn:
      "Coca-Cola sells a feeling of happiness, not just sugar water. It's sweet, fizzy and super refreshing when cold, and many people think of happy moments when they drink it. Its red can and curved bottle are recognized at a glance.",
    money: "一瓶可乐全世界卖得差不多便宜，靠的是“薄利多销”。成本主要是糖、水和瓶子，真正贵的是广告和品牌。公司在全球建工厂本地生产，省下运费，所以哪里都能买到又便宜又新鲜的可乐。",
    moneyEn:
      "A bottle of Coke sells for about the same cheap price worldwide thanks to 'small margin, huge volume'. The main costs are sugar, water and the bottle — what's really expensive is advertising and the brand. The company builds factories everywhere to produce locally, saving shipping, so fresh cheap Coke is available anywhere.",
    marketing: "可口可乐的广告总在讲“快乐”和“分享”，比如圣诞老人、家人团聚。它还把圣诞老人“穿”成了红色衣服——其实是广告画出来的！它让可乐不只是饮料，而是一种节日心情。",
    marketingEn:
      "Coca-Cola's ads always talk about happiness and sharing — like Santa Claus and family gatherings. It even 'dressed' Santa in a red suit — actually painted by its ads! It made Coke more than a drink: a holiday feeling.",
    competition: "可乐的老对手是百事可乐，两家斗了一百多年，叫“可乐大战”。百事更甜、更受年轻人喜欢；可口可乐更经典、全球第一。两家不停地比广告、比口味。",
    competitionEn:
      "Coke's old rival is Pepsi — the two have fought for over a hundred years in the 'Cola Wars'. Pepsi is sweeter and liked by young people; Coca-Cola is more classic and #1 worldwide. The two keep competing on ads and flavor.",
    funData: "全世界每天大约卖出19亿瓶可口可乐！如果排成一排能绕地球好几圈。它已经139岁了，比你爷爷的爷爷还老。",
    funDataEn:
      "About 1.9 billion bottles of Coca-Cola are sold every day worldwide! Lined up they'd wrap around the Earth several times. It's 139 years old — older than your great-great-grandfather.",
    dataPoints: [
      { label: "每天售出", labelEn: "Sold daily", value: 19, unit: "亿瓶", unitEn: "bn bottles" },
      { label: "品牌年龄", labelEn: "Brand age", value: 139, unit: "年", unitEn: "yrs" },
      { label: "全球员工", labelEn: "Global staff", value: 79, unit: "万人", unitEn: "k" },
    ],
    timeline: [
      { year: "1886", title: "发明可乐", titleEn: "Coke invented", desc: "药剂师彭伯顿熬出第一锅糖浆", descEn: "Pharmacist Pemberton cooks the first syrup" },
      { year: "1892", title: "成立公司", titleEn: "Company founded", desc: "可口可乐公司正式诞生", descEn: "The Coca-Cola Company is born" },
      { year: "1985", title: "新可乐风波", titleEn: "New Coke blunder", desc: "换配方被骂，又改回经典口味", descEn: "A new recipe flops; it reverts to classic" },
      { year: "2007", title: "零度可乐", titleEn: "Coke Zero", desc: "推出零糖版，保留经典味道", descEn: "A zero-sugar version keeps the classic taste" },
    ],
  },
  {
    id: "mcdonalds",
    name: "麦当劳",
    nameEn: "McDonald's",
    slug: "mcdonalds",
    category: "food-beverage",
    logo: "🍔",
    color: "#FFC72C",
    slogan: "我就喜欢",
    sloganEn: "I'm Lovin' It",
    description: "金拱门标志的快餐之王，把汉堡卖到了全世界。",
    descriptionEn: "The golden-arches fast-food king that sold burgers to the world.",
    featured: true,
    founded: 1955,
    founder: "雷·克洛克",
    founderEn: "Ray Kroc",
    country: "美国",
    countryEn: "the United States",
    funFact: "麦当劳每天服务6800多万人次，比英国全国人口还多！金色“M”是全世界最熟悉的标志之一。",
    funFactEn: "McDonald's serves 68 million people a day — more than the whole UK population!",
    keyFacts: [
      "1940年麦当劳兄弟开汉堡店，1955年克洛克推广到全球",
      "巨无霸1968年诞生",
      "全球4.3万家店，每天6800万人次",
      "其实是“大房东”，靠加盟和收租赚钱",
    ],
    keyFactsEn: [
      "The McDonald brothers opened a burger shop in 1940; Kroc took it global in 1955",
      "The Big Mac was born in 1968",
      "About 43,000 stores worldwide, serving 68 million a day",
      "It's really a 'big landlord' — it earns via franchises and rent",
    ],
    story: "麦当劳兄弟在加州开了一家汉堡店，想让出餐又快又便宜。后来推销员雷·克洛克觉得这主意太棒了，帮他们把店开到全世界，最后买下了公司。金色的“M”拱门成了全世界最熟悉的标志之一。",
    storyEn:
      "The McDonald brothers opened a burger shop in California to make food fast and cheap. Salesman Ray Kroc loved the idea, helped take it worldwide, and eventually bought the company. The golden 'M' arches became one of the most familiar logos on Earth.",
    product: "麦当劳卖的是“标准化”的快乐：汉堡、薯条、可乐，全世界的味道几乎一样。秘诀是流程——每块薯条炸多久、每个汉堡放几片酸黄瓜都有规定，所以你在中国和美国吃到的巨无霸差不多。",
    productEn:
      "McDonald's sells standardized happiness: burgers, fries and Coke that taste almost the same everywhere. The secret is process — how long each fry is cooked and how many pickles go on each burger are all fixed rules, so a Big Mac in China is about the same as in America.",
    money: "麦当劳其实是个“大房东”：很多钱不是卖汉堡赚的，而是把店面租给加盟商收租金。房地产+加盟让它在全世界开了4万多家店，而且风险很小。",
    moneyEn:
      "McDonald's is really a 'big landlord': much of its money isn't from selling burgers but from renting stores to franchisees. Real estate plus franchising let it open 40,000+ stores worldwide with very little risk.",
    marketing: "麦当劳最懂小朋友：开心乐园餐送玩具、门口有滑梯、叔叔麦当劳会跳舞。它让孩子觉得去麦当劳=开心，长大了还会带自己的孩子去。",
    marketingEn:
      "McDonald's understands kids best: Happy Meals come with toys, there are slides at the door, and Ronald McDonald dances. It makes kids feel that McDonald's equals happiness — and they bring their own kids when they grow up.",
    competition: "对手有肯德基、汉堡王。在中国，肯德基比麦当劳更早、门店更多；但麦当劳的汉堡和早餐很受欢迎。两家都在比谁更懂本地口味。",
    competitionEn:
      "Its rivals include KFC and Burger King. In China, KFC arrived earlier and has more stores, but McDonald's burgers and breakfast are popular. Both compete on understanding local tastes.",
    funData: "麦当劳每天服务6800多万人次，比英国全国人口还多！每秒大约卖出75个汉堡，巨无霸一年能卖5.5亿个。",
    funDataEn:
      "McDonald's serves over 68 million people a day — more than the UK population! It sells about 75 burgers a second, and 550 million Big Macs a year.",
    dataPoints: [
      { label: "全球门店", labelEn: "Stores worldwide", value: 4.3, unit: "万家", unitEn: "k" },
      { label: "每天服务", labelEn: "Served daily", value: 6800, unit: "万人次", unitEn: "k visits" },
      { label: "每秒汉堡", labelEn: "Burgers/sec", value: 75, unit: "个", unitEn: "" },
    ],
    timeline: [
      { year: "1940", title: "第一家店", titleEn: "First store", desc: "麦当劳兄弟在加州开汉堡店", descEn: "The brothers open a burger shop in California" },
      { year: "1955", title: "克洛克加盟", titleEn: "Kroc joins", desc: "雷·克洛克开始全球扩张", descEn: "Ray Kroc begins global expansion" },
      { year: "1968", title: "巨无霸诞生", titleEn: "Big Mac born", desc: "双层牛肉汉堡登场", descEn: "The double beef burger debuts" },
      { year: "1990", title: "进入中国", titleEn: "Enters China", desc: "深圳开出中国第一家店", descEn: "China's first store opens in Shenzhen" },
    ],
  },
  {
    id: "starbucks",
    name: "星巴克",
    nameEn: "Starbucks",
    slug: "starbucks",
    category: "food-beverage",
    logo: "☕",
    color: "#00704A",
    slogan: "第三空间",
    sloganEn: "The Third Place",
    description: "把咖啡馆变成“家和公司之外的第三空间”。",
    descriptionEn: "Turned cafés into a 'third place' between home and work.",
    featured: true,
    founded: 1971,
    founder: "鲍克 / 西格尔 / 鲍德温",
    founderEn: "Baldwin / Siegl / Bowker",
    country: "美国",
    countryEn: "the United States",
    funFact: "星巴克名字来自小说《白鲸》里的大副，美人鱼logo是双尾海妖。最早只卖咖啡豆，不卖杯装咖啡。",
    funFactEn: "Starbucks is named after a character in Moby-Dick; the logo is a two-tailed mermaid.",
    keyFacts: [
      "1971年西雅图首店，最初只卖咖啡豆",
      "舒尔茨引入意大利咖啡馆文化",
      "全球3.8万家店，中国超7000家",
      "对手瑞幸用便宜+小程序猛追",
    ],
    keyFactsEn: [
      "First store in Seattle in 1971, originally selling only beans",
      "Howard Schultz brought Italian café culture in",
      "About 38,000 stores worldwide, 7,000+ in China",
      "Rival Luckin chases hard with low prices and an app",
    ],
    story: "1971年，三个喜欢咖啡的美国人在西雅图开了一家小店，名字取自小说《白鲸》里的大副。那时候他们只卖咖啡豆，不卖杯装咖啡。后来舒尔茨加入，他去意大利看到咖啡馆文化，决定把“第三空间”带回美国，星巴克才变成今天的样子。",
    storyEn:
      "In 1971, three coffee-loving Americans opened a small shop in Seattle, named after an officer in the novel Moby-Dick. Back then they only sold beans, not cups of coffee. Later Howard Schultz joined, saw café culture in Italy, and decided to bring the 'third place' back to America — turning Starbucks into what it is today.",
    product: "星巴克卖的是“第三空间”——除了家和公司，另一个可以舒服坐着的地方。咖啡可以按你的口味定制，店里有Wi-Fi和音乐，杯子还写上你的名字。",
    productEn:
      "Starbucks sells a 'third place' — somewhere comfortable to sit that isn't home or work. Coffee can be customized to your taste, there's Wi-Fi and music, and they write your name on the cup.",
    money: "一杯星巴克咖啡的豆子和奶成本不高，但它靠品牌和服务卖出好几倍价格。会员卡和星礼卡让大家常来常买，在中国门店数超过7000家。",
    moneyEn:
      "The beans and milk in a Starbucks coffee don't cost much, but it charges several times more thanks to its brand and service. Membership and gift cards keep people coming back, and it has over 7,000 stores in China.",
    marketing: "星巴克把店员叫“伙伴”，杯子上写名字让你觉得被记得。美人鱼logo和绿色很显眼，发朋友圈特别好看，成了“社交货币”。",
    marketingEn:
      "Starbucks calls its staff 'partners' and writes your name on the cup so you feel remembered. The mermaid logo and green color stand out, look great on social media, and became 'social currency'.",
    competition: "对手有瑞幸、Costa。在中国，瑞幸用便宜+外卖+小程序抢走很多人，门店数甚至超过星巴克；但星巴克靠空间和体验仍有忠实粉丝。",
    competitionEn:
      "Rivals include Luckin and Costa. In China, Luckin wins many customers with low prices, delivery and an app — even surpassing Starbucks in store count — but Starbucks keeps loyal fans through space and experience.",
    funData: "星巴克全球有3.8万家店，中国就有7000多家，几乎每个大城市都有。它一年要用掉几亿升牛奶。",
    funDataEn:
      "Starbucks has about 38,000 stores worldwide, with 7,000+ in China — almost every big city has one. It uses hundreds of millions of litres of milk a year.",
    dataPoints: [
      { label: "全球门店", labelEn: "Stores worldwide", value: 3.8, unit: "万家", unitEn: "k" },
      { label: "中国门店", labelEn: "Stores in China", value: 7000, unit: "家", unitEn: "" },
      { label: "杯型选择", labelEn: "Cup sizes", value: 7, unit: "种", unitEn: "" },
    ],
    timeline: [
      { year: "1971", title: "西雅图首店", titleEn: "First Seattle store", desc: "只卖咖啡豆的小店", descEn: "A small shop selling only beans" },
      { year: "1987", title: "舒尔茨买下", titleEn: "Schultz buys it", desc: "转型现磨咖啡馆", descEn: "Shifts to freshly brewed coffee" },
      { year: "1999", title: "进入中国", titleEn: "Enters China", desc: "北京国贸开出首店", descEn: "First store at Beijing China World" },
      { year: "2024", title: "中国破七千", titleEn: "7,000 in China", desc: "中国门店超7000家", descEn: "China stores top 7,000" },
    ],
  },
  {
    id: "lays",
    name: "乐事",
    nameEn: "Lay's",
    slug: "lays",
    category: "food-beverage",
    logo: "🥔",
    color: "#F1471E",
    slogan: "片刻不停",
    sloganEn: "Betcha Can't Eat Just One",
    description: "黄色包装的薯片大王，口号是“只吃一片停不下来”。",
    descriptionEn: "The potato-chip king whose slogan dares you to eat just one.",
    founded: 1932,
    founder: "赫尔曼·雷",
    founderEn: "Herman Lay",
    country: "美国",
    countryEn: "the United States",
    funFact: "乐事的口号就是“只吃一片停不下来”，因为它又脆又香，真的很难停下来。",
    funFactEn: "Lay's slogan dares you to eat just one — its crunch makes it hard to stop.",
    keyFacts: [
      "1932年由赫尔曼·雷在美国创立",
      "土豆切片油炸，又脆又香",
      "全球各地有本地口味，如中国黄瓜味、泰国海苔味",
      "属于百事公司旗下",
    ],
    keyFactsEn: [
      "Founded in the US in 1932 by Herman Lay",
      "Potatoes sliced and fried for a crispy, tasty chip",
      "Local flavors worldwide, like Chinese cucumber and Thai seaweed",
      "Part of PepsiCo",
    ],
  },
  {
    id: "yili",
    name: "伊利",
    nameEn: "Yili",
    slug: "yili",
    category: "food-beverage",
    logo: "🥛",
    color: "#005BAC",
    slogan: "滋养生命活力",
    sloganEn: "Nourishing Life",
    description: "中国最大的乳业品牌之一，牛奶酸奶卖到千家万户。",
    descriptionEn: "One of China's biggest dairy brands, in millions of homes.",
    founded: 1993,
    founder: "郑俊怀（初创团队）",
    founderEn: "Zheng Junhuai (founding team)",
    country: "中国",
    countryEn: "China",
    funFact: "中国人喝的牛奶里，相当一部分来自伊利，它有自己的牧场和奶牛。",
    funFactEn: "Much of the milk Chinese people drink comes from Yili's own farms and cows.",
    keyFacts: [
      "1993年成立，总部在内蒙古呼和浩特",
      "有自有牧场，从挤奶到出厂全程可控",
      "产品有纯牛奶、酸奶、冰淇淋、奶粉",
      "连续多年是中国乳业第一",
    ],
    keyFactsEn: [
      "Founded in 1993, HQ in Hohhot, Inner Mongolia",
      "Owns its farms, controlling the whole process from milking to shipping",
      "Products include milk, yogurt, ice cream and milk powder",
      "China's #1 dairy brand for many years",
    ],
  },

  // ───────────────────────── Entertainment ─────────────────────────
  {
    id: "disney",
    name: "迪士尼",
    nameEn: "Disney",
    slug: "disney",
    category: "entertainment",
    logo: "🏰",
    color: "#1A6FB0",
    slogan: "世界上最快乐的地方",
    sloganEn: "The Happiest Place on Earth",
    description: "从一只米老鼠开始的魔法王国，造梦一百年。",
    descriptionEn: "A magic kingdom that started with a mouse and has been making dreams for 100 years.",
    featured: true,
    founded: 1923,
    founder: "华特·迪士尼",
    founderEn: "Walt Disney",
    country: "美国",
    countryEn: "the United States",
    funFact: "米老鼠最早叫“莫蒂默”，是迪士尼太太建议改成“米奇”的。",
    funFactEn: "Mickey Mouse was almost named Mortimer — Disney's wife suggested Mickey.",
    keyFacts: [
      "1923年华特·迪士尼创立",
      "1928年米奇在《汽船威利》首映",
      "6座主题乐园、60多部动画长片",
      "收购了皮克斯、漫威、星战",
    ],
    keyFactsEn: [
      "Founded by Walt Disney in 1923",
      "Mickey debuted in 'Steamboat Willie' in 1928",
      "6 theme parks and 60+ animated films",
      "Acquired Pixar, Marvel and Star Wars",
    ],
    story: "1923年，华特·迪士尼带着一只老鼠的梦想来到好莱坞。他画的米老鼠1928年在《汽船威利》里第一次说话，轰动世界。后来他又造了主题乐园、收购了皮克斯和漫威，把一个动画工作室变成了魔法王国。",
    storyEn:
      "In 1923, Walt Disney came to Hollywood with a mouse of a dream. The Mickey Mouse he drew first spoke in 'Steamboat Willie' in 1928 and stunned the world. Later he built theme parks and bought Pixar and Marvel, turning an animation studio into a magic kingdom.",
    product: "迪士尼卖的是“梦想成真”：电影让你哭让你笑，乐园让你走进故事里，周边让你把喜欢的角色带回家。它最厉害的是IP——米奇、公主、漫威英雄、星球大战，能拍电影、开乐园、卖玩具，一条龙。",
    productEn:
      "Disney sells dreams coming true: movies that make you laugh and cry, parks that let you step into stories, and merch that brings favorite characters home. Its superpower is IP — Mickey, princesses, Marvel heroes and Star Wars — which it turns into films, parks and toys, all in one chain.",
    money: "迪士尼的钱来自四面八方：电影票房、乐园门票和周边、Disney+会员、授权商品。一个米老鼠能反复赚几十年的钱，这叫“长青IP”。",
    moneyEn:
      "Disney's money comes from everywhere: box office, park tickets and merch, Disney+ subscriptions and licensing. A single Mickey can keep earning for decades — that's called an 'evergreen IP'.",
    marketing: "迪士尼最会说故事，让你和角色产生感情。乐园里每个员工都是“演员”，连扫地都像在表演。它让小朋友相信魔法是真的。",
    marketingEn:
      "Disney is the best storyteller, making you care about its characters. In its parks every employee is a 'cast member' — even sweeping the floor is a performance. It makes kids believe magic is real.",
    competition: "对手有环球影城（有哈利波特、小黄人）。环球更刺激、更成人；迪士尼更梦幻、更全家。两家在乐园和电影上一直比。",
    competitionEn:
      "Its rival is Universal Studios (with Harry Potter and Minions). Universal is more thrilling and grown-up; Disney is more dreamy and family-friendly. The two keep competing in parks and films.",
    funData: "迪士尼有6座主题乐园、60多部动画长片，米老鼠已经97岁了。迪士尼+上线5年就有1.5亿用户。",
    funDataEn:
      "Disney has 6 theme parks and 60+ animated films, and Mickey is 97 years old. Disney+ reached 150 million users within 5 years.",
    dataPoints: [
      { label: "主题乐园", labelEn: "Theme parks", value: 6, unit: "座", unitEn: "" },
      { label: "动画长片", labelEn: "Animated films", value: 60, unit: "多部", unitEn: "+" },
      { label: "米奇年龄", labelEn: "Mickey's age", value: 97, unit: "岁", unitEn: "yrs" },
    ],
    timeline: [
      { year: "1923", title: "公司成立", titleEn: "Company founded", desc: "华特·迪士尼兄弟工作室创立", descEn: "The Disney Brothers Studio is founded" },
      { year: "1928", title: "米奇首映", titleEn: "Mickey debuts", desc: "《汽船威利》轰动世界", descEn: "'Steamboat Willie' stuns the world" },
      { year: "1955", title: "迪士尼乐园", titleEn: "Disneyland", desc: "加州乐园开门迎客", descEn: "The California park opens" },
      { year: "2019", title: "迪士尼+", titleEn: "Disney+", desc: "流媒体上线，抢占线上", descEn: "The streaming service launches" },
    ],
  },
  {
    id: "lego",
    name: "乐高",
    nameEn: "LEGO",
    slug: "lego",
    category: "entertainment",
    logo: "🧱",
    color: "#DA291C",
    slogan: "只有最好的才够好",
    sloganEn: "Only the Best is Good Enough",
    description: "丹麦的积木王国，几块塑料就能拼出整个世界。",
    descriptionEn: "The Danish brick kingdom where a few plastic blocks build whole worlds.",
    featured: true,
    founded: 1932,
    founder: "奥莱·柯克·克里斯蒂安森",
    founderEn: "Ole Kirk Christiansen",
    country: "丹麦",
    countryEn: "Denmark",
    funFact: "“LEGO”来自丹麦语“leg godt”，意思是“玩得好”。两块乐高积木的咬合力能承受一个小孩的重量。",
    funFactEn: "'LEGO' comes from Danish 'leg godt' meaning 'play well'. Two bricks can hold a child's weight.",
    keyFacts: [
      "1932年从木制玩具起家",
      "1958年现代塑料积木获得专利",
      "和星战、哈利波特等IP合作",
      "全球最赚钱的玩具公司之一",
    ],
    keyFactsEn: [
      "Started with wooden toys in 1932",
      "The modern plastic brick was patented in 1958",
      "Partners with Star Wars, Harry Potter and more",
      "One of the world's most profitable toy companies",
    ],
    story: "1932年，丹麦木匠克里斯蒂安森在萧条时期靠做木玩具养家。他把公司叫“LEGO”，丹麦语“leg godt”就是“玩得好”。1958年他儿子发明了现在的塑料凸起积木，两块积木能紧紧咬在一起，从此乐高火遍全球。",
    storyEn:
      "In 1932, Danish carpenter Christiansen supported his family making wooden toys during hard times. He named the company 'LEGO', from the Danish 'leg godt' meaning 'play well'. In 1958 his son invented the modern stud-and-tube brick that clicks together firmly, and LEGO spread worldwide.",
    product: "乐高卖的是“创造力”：几块积木能拼出任何东西，从房子到宇宙飞船。它和星球大战、哈利波特合作，让你拼出电影里的世界。积木还能反复拆装，永不坏。",
    productEn:
      "LEGO sells creativity: a few bricks can build anything, from a house to a spaceship. It partners with Star Wars and Harry Potter so you can build movie worlds. Bricks can be taken apart and rebuilt forever — they never break.",
    money: "乐高靠卖套装赚钱，贵的几千块一套。它还做游戏、电影、乐园。积木生产成本不高，靠品牌和设计卖出高利润，是全球最赚钱的玩具公司之一。",
    moneyEn:
      "LEGO earns by selling sets — fancy ones cost a lot. It also makes games, films and parks. Brick production isn't costly, so it sells at high profit through brand and design — one of the world's most profitable toy companies.",
    marketing: "乐高让“拼”变成全家活动，盒子上印年龄但其实大人也爱玩。它还拍了大电影，让积木变成英雄，边玩边卖。",
    marketingEn:
      "LEGO turns building into a family activity — boxes show ages but adults love it too. It also made hit movies, turning bricks into heroes and selling while you play.",
    competition: "对手有更便宜的仿牌积木，但乐高靠质量和IP稳坐第一。它也和任天堂等公司合作出新玩法。",
    competitionEn:
      "Rivals include cheaper copycat bricks, but LEGO stays #1 through quality and IP. It also teams up with companies like Nintendo for new ways to play.",
    funData: "乐高一年生产750亿块积木，全球乐高人仔有100亿个，比地球人都多！6块2x4积木能拼出9.15亿种组合。",
    funDataEn:
      "LEGO makes 75 billion bricks a year, and there are 10 billion minifigures worldwide — more than people on Earth! Six 2x4 bricks can make 915 million combinations.",
    dataPoints: [
      { label: "年产积木", labelEn: "Bricks/year", value: 750, unit: "亿块", unitEn: "bn" },
      { label: "乐高人仔", labelEn: "Minifigures", value: 100, unit: "亿个", unitEn: "bn" },
      { label: "6块组合", labelEn: "Combos of 6", value: 915, unit: "百万种", unitEn: "M" },
    ],
    timeline: [
      { year: "1932", title: "木制玩具", titleEn: "Wooden toys", desc: "木匠克里斯蒂安森创业", descEn: "Carpenter Christiansen starts out" },
      { year: "1958", title: "现代积木", titleEn: "Modern brick", desc: "塑料凸起积木获得专利", descEn: "The stud brick is patented" },
      { year: "1968", title: "乐高乐园", titleEn: "LEGOLAND", desc: "丹麦比隆首家乐园", descEn: "First park in Billund, Denmark" },
      { year: "1999", title: "星战系列", titleEn: "Star Wars", desc: "开启IP合作时代", descEn: "The IP-partnership era begins" },
    ],
  },
  {
    id: "nintendo",
    name: "任天堂",
    nameEn: "Nintendo",
    slug: "nintendo",
    category: "entertainment",
    logo: "🎮",
    color: "#E60012",
    slogan: "创造独特的娱乐",
    sloganEn: "Create Unique Entertainment",
    description: "从做纸牌到做游戏机的百年老店，造了马里奥和塞尔达。",
    descriptionEn: "A 135-year-old company that went from playing cards to Mario and Zelda.",
    founded: 1889,
    founder: "山内房治郎",
    founderEn: "Fusajiro Yamauchi",
    country: "日本",
    countryEn: "Japan",
    funFact: "任天堂最早是做花札（日本纸牌）的，1889年成立，过了快80年才开始做游戏。",
    funFactEn: "Nintendo started in 1889 making Japanese playing cards — games came almost 80 years later.",
    keyFacts: [
      "1889年做花札纸牌起家",
      "1985年马里奥在《超级马里奥兄弟》登场",
      "Switch是全球最火的掌机之一",
      "角色IP：马里奥、塞尔达、宝可梦",
    ],
    keyFactsEn: [
      "Started making hanafuda cards in 1889",
      "Mario debuted in 'Super Mario Bros.' in 1985",
      "The Switch is one of the world's hottest consoles",
      "Character IP: Mario, Zelda, Pokémon",
    ],
  },
  {
    id: "popmart",
    name: "泡泡玛特",
    nameEn: "Pop Mart",
    slug: "popmart",
    category: "entertainment",
    logo: "🎁",
    color: "#FF2E55",
    slogan: "创造潮流，传递美好",
    sloganEn: "Create Trends, Share Beauty",
    description: "把潮玩装进盲盒，让拆盒子变成一场惊喜游戏。",
    descriptionEn: "Turned designer toys into blind boxes full of surprise.",
    founded: 2010,
    founder: "王宁",
    founderEn: "Wang Ning",
    country: "中国",
    countryEn: "China",
    funFact: "泡泡玛特把玩具做成“盲盒”，你买之前不知道是哪一款，拆开那一刻的惊喜才是重点。",
    funFactEn: "Pop Mart sells 'blind boxes' — you don't know which figure is inside until you open it.",
    keyFacts: [
      "2010年成立，总部北京",
      "签约Molly、Dimoo等设计师IP",
      "盲盒模式让拆盒变成惊喜",
      "开到了全球30多个国家",
    ],
    keyFactsEn: [
      "Founded in 2010, HQ in Beijing",
      "Signs designer IPs like Molly and Dimoo",
      "The blind-box model makes unboxing a surprise",
      "Now in 30+ countries worldwide",
    ],
  },
  {
    id: "universal-studios",
    name: "环球影城",
    nameEn: "Universal Studios",
    slug: "universal-studios",
    category: "entertainment",
    logo: "🎬",
    color: "#00BFA5",
    slogan: "走进电影世界",
    sloganEn: "Step Into the Movies",
    description: "从电影制片厂变成主题乐园，有哈利波特和小黄人。",
    descriptionEn: "A real film studio that became a theme park with Harry Potter and Minions.",
    founded: 1912,
    founder: "卡尔·莱姆勒",
    founderEn: "Carl Laemmle",
    country: "美国",
    countryEn: "the United States",
    funFact: "环球影城最早是真电影制片厂，游客坐着小火车去看拍电影，后来才变成主题乐园。",
    funFactEn: "Universal started as a real studio; visitors rode trams to watch filming before it became a park.",
    keyFacts: [
      "1912年成立电影公司",
      "1964年开放影城游览",
      "有哈利波特、小黄人、侏罗纪世界",
      "北京环球影城2021年开园",
    ],
    keyFactsEn: [
      "Founded as a film studio in 1912",
      "Opened the studio tour in 1964",
      "Home to Harry Potter, Minions and Jurassic World",
      "Universal Beijing opened in 2021",
    ],
  },

  // ───────────────────────── Technology ─────────────────────────
  {
    id: "apple",
    name: "苹果",
    nameEn: "Apple",
    slug: "apple",
    category: "technology",
    logo: "🍎",
    color: "#1D1D1F",
    slogan: "Think Different",
    sloganEn: "Think Different",
    description: "在车库里造电脑，把手机变成了人人离不开的工具。",
    descriptionEn: "From a garage-built computer to the phone nobody can live without.",
    featured: true,
    founded: 1976,
    founder: "乔布斯 / 沃兹尼亚克",
    founderEn: "Steve Jobs / Steve Wozniak",
    country: "美国",
    countryEn: "the United States",
    funFact: "第一台苹果电脑在车库里造出来，售价666.66美元。苹果是第一个市值破万亿美元的美国公司之一。",
    funFactEn: "The first Apple computer was built in a garage and sold for $666.66.",
    keyFacts: [
      "1976年车库创业",
      "2007年发布iPhone改变手机",
      "iOS/macOS生态把用户留住",
      "市值曾超3万亿美元",
    ],
    keyFactsEn: [
      "Started in a garage in 1976",
      "The 2007 iPhone changed phones forever",
      "The iOS/macOS ecosystem keeps users in",
      "Market value once topped $3 trillion",
    ],
    story: "1976年，乔布斯和沃兹尼亚克在车库里造出第一台苹果电脑，卖给了商店。乔布斯曾一度被自己公司赶走，又回来拯救苹果，做出iPod、iPhone，把一家快倒闭的公司变成全球最值钱的公司之一。",
    storyEn:
      "In 1976, Jobs and Wozniak built the first Apple computer in a garage and sold it to shops. Jobs was once kicked out of his own company, then came back to save Apple, making the iPod and iPhone — turning a nearly-bankrupt company into one of the world's most valuable.",
    product: "苹果卖的是“好用又好看”。iPhone一个按钮就能用，Mac漂亮又流畅，AirPods一开盖就连上。它把复杂的技术藏起来，让你觉得简单。",
    productEn:
      "Apple sells easy and beautiful. The iPhone works with one button, the Mac is pretty and smooth, AirPods connect the moment you open the case. It hides the complicated tech so everything feels simple.",
    money: "苹果靠卖硬件赚大钱，iPhone一部能赚好几千。它还有App Store抽成、iCloud订阅，软件也持续赚钱。市值曾超过3万亿美元，富可敌国。",
    moneyEn:
      "Apple makes big money selling hardware — each iPhone earns thousands. It also takes a cut on the App Store and iCloud subscriptions, so software keeps earning. Its value once topped $3 trillion, richer than many countries.",
    marketing: "苹果的广告很酷：黑背景、一句口号、一个产品。“Think Different”讲的是改变世界的人。它让你觉得用苹果=有品味。",
    marketingEn:
      "Apple's ads are cool: black background, one slogan, one product. 'Think Different' celebrated people who changed the world. It makes using Apple feel like having taste.",
    competition: "对手手机有三星、华为、小米；电脑有微软。苹果靠自己的系统（iOS/macOS）和生态把用户留住，换出去就很难。",
    competitionEn:
      "Phone rivals include Samsung, Huawei and Xiaomi; in computers, Microsoft. Apple keeps users with its own systems (iOS/macOS) and ecosystem — once you're in, it's hard to leave.",
    funData: "苹果已经卖出23亿部iPhone，全球有520家Apple Store。它的现金一度比美国政府还多。",
    funDataEn:
      "Apple has sold 2.3 billion iPhones and has 520 Apple Stores worldwide. Its cash once topped the US government's.",
    dataPoints: [
      { label: "iPhone累计", labelEn: "iPhones sold", value: 23, unit: "亿部", unitEn: "bn" },
      { label: "全球门店", labelEn: "Stores worldwide", value: 520, unit: "家", unitEn: "" },
      { label: "市值峰值", labelEn: "Peak value", value: 3, unit: "万亿美元", unitEn: "trn USD" },
    ],
    timeline: [
      { year: "1976", title: "车库创业", titleEn: "Garage start", desc: "Apple I在车库里诞生", descEn: "Apple I is born in a garage" },
      { year: "1984", title: "麦金塔", titleEn: "Macintosh", desc: "Mac带来图形界面", descEn: "The Mac brings a graphical interface" },
      { year: "2001", title: "iPod", titleEn: "iPod", desc: "一千首歌装进口袋", descEn: "1,000 songs in your pocket" },
      { year: "2007", title: "iPhone", titleEn: "iPhone", desc: "重新发明手机", descEn: "The phone, reinvented" },
    ],
  },
  {
    id: "google",
    name: "谷歌",
    nameEn: "Google",
    slug: "google",
    category: "technology",
    logo: "🔍",
    color: "#4285F4",
    slogan: "组织全世界的信息",
    sloganEn: "Organize the World's Information",
    description: "全球最大的搜索引擎，也是安卓手机和YouTube的老板。",
    descriptionEn: "The world's biggest search engine, plus Android and YouTube.",
    founded: 1998,
    founder: "拉里·佩奇 / 谢尔盖·布林",
    founderEn: "Larry Page / Sergey Brin",
    country: "美国",
    countryEn: "the United States",
    funFact: "“Google”其实是“Googol”的拼写错误，googol是1后面100个0那么大的数。",
    funFactEn: "'Google' is a misspelling of 'Googol' — the number 1 followed by 100 zeros.",
    keyFacts: [
      "1998年在车库里成立",
      "靠搜索广告赚大钱",
      "旗下有安卓、YouTube、Chrome",
      "母公司叫Alphabet",
    ],
    keyFactsEn: [
      "Founded in a garage in 1998",
      "Makes big money from search ads",
      "Owns Android, YouTube and Chrome",
      "Its parent company is called Alphabet",
    ],
  },
  {
    id: "microsoft",
    name: "微软",
    nameEn: "Microsoft",
    slug: "microsoft",
    category: "technology",
    logo: "🪟",
    color: "#00A4EF",
    slogan: "赋能每个人",
    sloganEn: "Empower Every Person",
    description: "让每张桌子上都有一台电脑的公司，做了Windows和Office。",
    descriptionEn: "The company that put a computer on every desk, making Windows and Office.",
    founded: 1975,
    founder: "比尔·盖茨 / 保罗·艾伦",
    founderEn: "Bill Gates / Paul Allen",
    country: "美国",
    countryEn: "the United States",
    funFact: "微软最早是为个人电脑写BASIC语言解释器；Windows最初的名字叫“Interface Manager”。",
    funFactEn: "Microsoft started writing BASIC interpreters; Windows was first called 'Interface Manager'.",
    keyFacts: [
      "1975年盖茨和艾伦创立",
      "Windows和Office统治电脑桌面",
      "现在主攻云Azure和AI",
      "投资了OpenAI",
    ],
    keyFactsEn: [
      "Founded by Gates and Allen in 1975",
      "Windows and Office rule the desktop",
      "Now focused on Azure cloud and AI",
      "Invested in OpenAI",
    ],
  },
  {
    id: "dji",
    name: "大疆",
    nameEn: "DJI",
    slug: "dji",
    category: "technology",
    logo: "🚁",
    color: "#1D1D1F",
    slogan: "未来无所不能",
    sloganEn: "The Future of Possible",
    description: "中国的无人机之王，让天上飞的小飞机走进千家万户。",
    descriptionEn: "China's drone king that put flying cameras in everyday hands.",
    founded: 2006,
    founder: "汪滔",
    founderEn: "Frank Wang",
    country: "中国",
    countryEn: "China",
    funFact: "全球每10架消费级无人机里，大约7架是大疆造的，它在宿舍里起家。",
    funFactEn: "About 7 of every 10 consumer drones worldwide are made by DJI, which started in a dorm.",
    keyFacts: [
      "2006年在大学宿舍创办",
      "全球消费级无人机市占率第一",
      "产品有航拍机、农业机、运动相机",
      "总部在深圳",
    ],
    keyFactsEn: [
      "Founded in a college dorm in 2006",
      "#1 global market share in consumer drones",
      "Makes camera drones, farm drones and action cams",
      "HQ in Shenzhen",
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    nameEn: "OpenAI",
    slug: "openai",
    category: "technology",
    logo: "🤖",
    color: "#10A37F",
    slogan: "安全的通用人工智能",
    sloganEn: "Safe AGI",
    description: "做出ChatGPT的公司，让AI能像人一样聊天写文章。",
    descriptionEn: "The lab behind ChatGPT, making AI chat and write like a human.",
    founded: 2015,
    founder: "山姆·奥特曼 等",
    founderEn: "Sam Altman et al.",
    country: "美国",
    countryEn: "the United States",
    funFact: "ChatGPT上线5天就有100万用户，是史上增长最快的应用之一。",
    funFactEn: "ChatGPT hit 1 million users in 5 days — one of the fastest ever.",
    keyFacts: [
      "2015年成立",
      "2022年发布ChatGPT引爆AI",
      "模型：GPT系列、DALL·E、Sora",
      "微软是大投资人",
    ],
    keyFactsEn: [
      "Founded in 2015",
      "Released ChatGPT in 2022, igniting the AI boom",
      "Models: the GPT family, DALL·E and Sora",
      "Microsoft is a major investor",
    ],
  },

  // ───────────────────────── Sports ─────────────────────────
  {
    id: "nike",
    name: "耐克",
    nameEn: "Nike",
    slug: "nike",
    category: "sports",
    logo: "👟",
    color: "#111111",
    slogan: "Just Do It",
    sloganEn: "Just Do It",
    description: "一个35美元画出来的对勾，成了运动世界第一标志。",
    descriptionEn: "A $35 check-mark doodle that became sports' #1 logo.",
    featured: true,
    founded: 1964,
    founder: "菲尔·奈特 / 比尔·鲍尔曼",
    founderEn: "Phil Knight / Bill Bowerman",
    country: "美国",
    countryEn: "the United States",
    funFact: "耐克名字来自希腊胜利女神；标志是花35美元请学生画的“swoosh”对勾。",
    funFactEn: "Nike is named after the Greek goddess of victory; the swoosh cost $35 from a student.",
    keyFacts: [
      "1964年叫蓝带体育，1971年改名Nike",
      "签约乔丹、科比、C罗",
      "气垫等运动科技领先",
      "年营收超500亿美元",
    ],
    keyFactsEn: [
      "Called Blue Ribbon Sports in 1964, renamed Nike in 1971",
      "Signs Jordan, Kobe and Cristiano Ronaldo",
      "Leads in sports tech like air cushions",
      "Annual revenue over $50 billion",
    ],
    story: "1964年，跑步教练鲍尔曼和学生奈特合作卖跑鞋，公司最早叫“蓝带体育”。1971年改名Nike——希腊胜利女神，还花35美元请学生画了个“对勾”标志。今天这个swoosh是全世界最贵的标志之一。",
    storyEn:
      "In 1964, running coach Bowerman and his student Knight teamed up to sell running shoes, first calling the company 'Blue Ribbon Sports'. In 1971 they renamed it Nike — the Greek goddess of victory — and paid a student $35 to draw a 'check mark' logo. Today that swoosh is one of the most valuable logos in the world.",
    product: "耐克卖的是“更厉害的你”。球鞋有气垫让你跳更高，衣服让你跑更舒服。它和乔丹、科比、C罗合作，让你觉得穿上就能像偶像一样。",
    productEn:
      "Nike sells a better you. Shoes with air cushions help you jump higher, clothes make running more comfortable. It partners with Jordan, Kobe and Ronaldo so you feel you can be like your heroes.",
    money: "耐克靠卖鞋服赚钱，一双球鞋成本不高但卖好几百上千。签约球星和球队是它的广告，也是它的护城河。年营收超过500亿美元。",
    moneyEn:
      "Nike earns by selling shoes and clothes — a shoe doesn't cost much to make but sells for hundreds or thousands. Signing stars and teams is both its advertising and its moat. Annual revenue tops $50 billion.",
    marketing: "“Just Do It”三个词激励全世界去运动。耐克签下最棒的运动员，让你相信好运动员都穿耐克。限量球鞋还能炒到几万块。",
    marketingEn:
      "'Just Do It' — three words that inspire the world to move. Nike signs the best athletes so you believe great athletes all wear Nike. Limited shoes can even resell for huge money.",
    competition: "对手是阿迪达斯，两家斗了几十年。安踏、李宁在中国崛起；但耐克靠球星和科技仍是全球第一。",
    competitionEn:
      "Its rival is Adidas — the two have fought for decades. Anta and Li-Ning are rising in China, but Nike stays #1 worldwide thanks to stars and tech.",
    funData: "耐克一年营收514亿美元，全球7.9万名员工。它那个35美元的对勾logo，现在价值连城。",
    funDataEn:
      "Nike's annual revenue is $51.4 billion, with 79,000 employees worldwide. That $35 swoosh is now worth a fortune.",
    dataPoints: [
      { label: "年营收", labelEn: "Annual revenue", value: 514, unit: "亿美元", unitEn: "bn USD" },
      { label: "全球员工", labelEn: "Global staff", value: 79, unit: "千人", unitEn: "k" },
      { label: "logo设计费", labelEn: "Logo cost", value: 35, unit: "美元", unitEn: "USD" },
    ],
    timeline: [
      { year: "1964", title: "蓝带体育", titleEn: "Blue Ribbon Sports", desc: "教练和学生合作卖跑鞋", descEn: "Coach and student sell running shoes" },
      { year: "1971", title: "改名Nike", titleEn: "Renamed Nike", desc: "诞生swoosh对勾标志", descEn: "The swoosh is born" },
      { year: "1988", title: "Just Do It", titleEn: "Just Do It", desc: "三大字口号问世", descEn: "The three-word slogan arrives" },
      { year: "2024", title: "全球第一", titleEn: "#1 worldwide", desc: "稳坐运动品牌头把交椅", descEn: "Sits atop sports brands" },
    ],
  },
  {
    id: "adidas",
    name: "阿迪达斯",
    nameEn: "Adidas",
    slug: "adidas",
    category: "sports",
    logo: "👟",
    color: "#000000",
    slogan: "Impossible Is Nothing",
    sloganEn: "Impossible Is Nothing",
    description: "三条杠的运动巨头，和耐克斗了几十年。",
    descriptionEn: "The three-stripes sports giant, Nike's rival for decades.",
    founded: 1949,
    founder: "阿迪·达斯勒",
    founderEn: "Adi Dassler",
    country: "德国",
    countryEn: "Germany",
    funFact: "阿迪达斯名字来自创始人Adi Dassler的缩写；他的哥哥创办了对手Puma，两兄弟成了对手。",
    funFactEn: "Adidas comes from founder Adi Dassler; his brother founded rival Puma.",
    keyFacts: [
      "1949年在德国成立",
      "三条杠标志深入人心",
      "足球装备很强，赞助世界杯球队",
      "哥哥创办了Puma，兄弟成对手",
    ],
    keyFactsEn: [
      "Founded in Germany in 1949",
      "The three-stripes logo is iconic",
      "Strong in football gear, sponsoring World Cup teams",
      "His brother founded Puma — siblings became rivals",
    ],
  },
  {
    id: "anta",
    name: "安踏",
    nameEn: "Anta",
    slug: "anta",
    category: "sports",
    logo: "🏃",
    color: "#C8102E",
    slogan: "永不止步",
    sloganEn: "Keep Moving",
    description: "中国运动品牌一哥，收购了FILA还赞助了奥运。",
    descriptionEn: "China's #1 sports brand, owner of FILA and Olympic sponsor.",
    founded: 1991,
    founder: "丁世忠",
    founderEn: "Ding Shizhong",
    country: "中国",
    countryEn: "China",
    funFact: "安踏收购了FILA中国，还是中国奥运代表团的赞助商，给运动员做领奖服。",
    funFactEn: "Anta bought FILA China and makes the Chinese Olympic team's award uniforms.",
    keyFacts: [
      "1991年福建晋江起家",
      "收购FILA中国，多品牌运营",
      "中国奥运代表团赞助商",
      "中国运动品牌营收第一",
    ],
    keyFactsEn: [
      "Started in Jinjiang, Fujian in 1991",
      "Bought FILA China, runs multiple brands",
      "Sponsor of China's Olympic team",
      "#1 sports brand in China by revenue",
    ],
  },
  {
    id: "li-ning",
    name: "李宁",
    nameEn: "Li-Ning",
    slug: "li-ning",
    category: "sports",
    logo: "🤸",
    color: "#C8102E",
    slogan: "一切皆有可能",
    sloganEn: "Anything is Possible",
    description: "“体操王子”李宁创立的品牌，2008奥运飞天点火炬。",
    descriptionEn: "Founded by 'Prince of Gymnastics' Li Ning, who lit the 2008 Olympic flame mid-air.",
    founded: 1990,
    founder: "李宁",
    founderEn: "Li Ning",
    country: "中国",
    countryEn: "China",
    funFact: "创始人李宁是“体操王子”，2008年北京奥运会他飞天点燃主火炬，震惊世界。",
    funFactEn: "Founder Li Ning, the 'Prince of Gymnastics', flew through the air to light the 2008 Olympic flame.",
    keyFacts: [
      "1990年由体操王子李宁创立",
      "2008奥运飞天点火炬",
      "国潮设计受年轻人喜欢",
      "产品有运动鞋服、器材",
    ],
    keyFactsEn: [
      "Founded in 1990 by 'Prince of Gymnastics' Li Ning",
      "Lit the 2008 Olympic flame mid-air",
      "Its China-chic designs are loved by young people",
      "Products include shoes, apparel and gear",
    ],
  },

  // ───────────────────────── Retail ─────────────────────────
  {
    id: "ikea",
    name: "宜家",
    nameEn: "IKEA",
    slug: "ikea",
    category: "retail",
    logo: "🛋️",
    color: "#0058A3",
    slogan: "为大众创造美好日常",
    sloganEn: "A Better Everyday Life",
    description: "蓝黄大仓库里的家具王国，要自己搬回家自己装。",
    descriptionEn: "The blue-and-yellow furniture kingdom where you haul and build it yourself.",
    founded: 1943,
    founder: "英格瓦·坎普拉德",
    founderEn: "Ingvar Kamprad",
    country: "瑞典",
    countryEn: "Sweden",
    funFact: "宜家名字是创始人姓名首字母+他长大的农场名；家具要自己搬回家自己装，所以便宜。",
    funFactEn: "IKEA's name is the founder's initials plus his farm; flat-pack furniture you build yourself keeps it cheap.",
    keyFacts: [
      "1943年瑞典成立",
      "平板包装+自己组装=便宜",
      "店里有样板间和1元冰淇淋",
      "全球50多个国家有店",
    ],
    keyFactsEn: [
      "Founded in Sweden in 1943",
      "Flat-pack + self-assembly = cheap",
      "Stores have showrooms and 1-yuan ice cream",
      "Stores in 50+ countries",
    ],
  },
  {
    id: "walmart",
    name: "沃尔玛",
    nameEn: "Walmart",
    slug: "walmart",
    category: "retail",
    logo: "🛒",
    color: "#0071CE",
    slogan: "省钱·生活更好",
    sloganEn: "Save Money. Live Better.",
    description: "靠“天天低价”做成全球最大零售商之一。",
    descriptionEn: "Grew into one of the world's biggest retailers on 'everyday low prices'.",
    founded: 1962,
    founder: "山姆·沃尔顿",
    founderEn: "Sam Walton",
    country: "美国",
    countryEn: "the United States",
    funFact: "沃尔玛是全球最大的公司之一，靠“天天低价”打败对手，一周有上亿人光顾。",
    funFactEn: "Walmart is one of the world's biggest companies; over 100 million shop there each week.",
    keyFacts: [
      "1962年山姆·沃尔顿创立",
      "天天低价策略",
      "全球最大零售商之一",
      "旗下有山姆会员店",
    ],
    keyFactsEn: [
      "Founded by Sam Walton in 1962",
      "Everyday-low-prices strategy",
      "One of the world's biggest retailers",
      "Owns Sam's Club",
    ],
  },
  {
    id: "miniso",
    name: "名创优品",
    nameEn: "Miniso",
    slug: "miniso",
    category: "retail",
    logo: "🛍️",
    color: "#E60012",
    slogan: "让生活更美好",
    sloganEn: "Life is for Fun",
    description: "10元起步的小商品店，开到了全世界100多个国家。",
    descriptionEn: "A small-goods store starting at 10 yuan, now in 100+ countries.",
    founded: 2013,
    founder: "叶国富",
    founderEn: "Ye Guofu",
    country: "中国",
    countryEn: "China",
    funFact: "名创优品从10元小商品做起，开到了全世界100多个国家，还和三丽鸥、迪士尼联名。",
    funFactEn: "Miniso started with 10-yuan goods, reached 100+ countries, and partners with Disney and Sanrio.",
    keyFacts: [
      "2013年成立，总部广州",
      "10元起的小商品+IP联名",
      "全球100多个国家有店",
      "和迪士尼、三丽鸥合作",
    ],
    keyFactsEn: [
      "Founded in 2013, HQ in Guangzhou",
      "Low-price goods + IP collaborations",
      "Stores in 100+ countries",
      "Partners with Disney and Sanrio",
    ],
  },
  {
    id: "7-eleven",
    name: "7-Eleven",
    nameEn: "7-Eleven",
    slug: "7-eleven",
    category: "retail",
    logo: "🏪",
    color: "#2A8D1F",
    slogan: "随时都在你身边",
    sloganEn: "Always There for You",
    description: "名字来自早7到晚11的便利店，现在很多店24小时营业。",
    descriptionEn: "Named for 7am-to-11pm hours, though many stores now run 24/7.",
    founded: 1927,
    founder: "南方制冰公司",
    founderEn: "Southland Ice Company",
    country: "美国 / 日本",
    countryEn: "USA / Japan",
    funFact: "7-Eleven名字来自营业时间早7点到晚11点，现在很多店24小时营业，半夜也能买东西。",
    funFactEn: "7-Eleven is named for 7am-11pm hours, though many now stay open 24 hours.",
    keyFacts: [
      "1927年在美国达拉斯起家",
      "名字来自早7到晚11的营业时间",
      "全球最大便利店连锁",
      "日本7-Eleven以鲜食闻名",
    ],
    keyFactsEn: [
      "Started in Dallas, USA in 1927",
      "Named for 7am-to-11pm hours",
      "The world's biggest convenience-store chain",
      "Japan's 7-Eleven is famous for fresh food",
    ],
  },

  // ───────────────────────── Transport ─────────────────────────
  {
    id: "tesla",
    name: "特斯拉",
    nameEn: "Tesla",
    slug: "tesla",
    category: "transport",
    logo: "🚗",
    color: "#E82127",
    slogan: "加速世界向可持续能源",
    sloganEn: "Accelerate Sustainable Energy",
    description: "把电动车做成潮品的硅谷车企，车能像手机一样升级。",
    descriptionEn: "The Silicon Valley carmaker that made EVs cool and updatable like phones.",
    featured: true,
    founded: 2003,
    founder: "埃伯哈德 / 塔彭宁（马斯克投资）",
    founderEn: "Eberhard / Tarpenning (Musk invested)",
    country: "美国",
    countryEn: "the United States",
    funFact: "特斯拉不打广告、不打折，车子还能像手机一样“升级系统”变聪明。",
    funFactEn: "Tesla spends almost nothing on ads and updates its cars like a phone.",
    keyFacts: [
      "2003年几个工程师创办",
      "马斯克投资并领导公司",
      "Model 3是史上最畅销电车之一",
      "上海超级工厂供应全球",
    ],
    keyFactsEn: [
      "Founded by a few engineers in 2003",
      "Elon Musk invested and leads the company",
      "The Model 3 is one of the best-selling EVs ever",
      "The Shanghai Gigafactory supplies the world",
    ],
    story: "2003年几个工程师想造一辆又酷又快的电动车，证明电车不丑也不慢。后来马斯克投资并领导公司，造出Roadster、Model S，让电动车变成潮品，还建了超级工厂。",
    storyEn:
      "In 2003 a few engineers wanted to build a cool, fast electric car to prove EVs weren't ugly or slow. Later Elon Musk invested and led the company, building the Roadster and Model S, making EVs cool, and building Gigafactories.",
    product: "特斯拉卖的是“会跑的智能设备”。车子加速快、不用加油、还能自己开一点。它能像手机一样升级系统，今天变聪明一点，明天多个新功能。",
    productEn:
      "Tesla sells a smart device that drives. The cars accelerate fast, need no gas, and can even drive themselves a little. They update like a phone — a bit smarter today, a new feature tomorrow.",
    money: "特斯拉靠卖车赚钱，还卖充电、软件（自动驾驶）。它直营不找经销商，价格透明。上海工厂让它在中国又便宜又快地交车。",
    moneyEn:
      "Tesla earns by selling cars, plus charging and software (self-driving). It sells directly with no dealers, so prices are transparent. The Shanghai factory lets it deliver in China cheaply and fast.",
    marketing: "特斯拉几乎不打广告——老板马斯克自己就是广告，发条推特全世界都在看。它让人觉得开电车=未来、=酷。",
    marketingEn:
      "Tesla runs almost no ads — boss Musk is the ad himself, and one tweet is watched worldwide. It makes driving an EV feel like the future and cool.",
    competition: "对手有比亚迪（中国销量第一）、蔚来、小鹏。比亚迪靠电池和便宜车型猛追；特斯拉靠品牌和自动驾驶。",
    competitionEn:
      "Rivals include BYD (#1 in China sales), NIO and XPeng. BYD chases hard with batteries and cheap models; Tesla leans on brand and self-driving.",
    funData: "特斯拉2023年交付181万辆车，全球有6万多个超充桩。Model 3是史上最畅销的电动车之一。",
    funDataEn:
      "Tesla delivered 1.81 million cars in 2023 and has 60,000+ Superchargers worldwide. The Model 3 is one of the best-selling EVs ever.",
    dataPoints: [
      { label: "2023交付", labelEn: "2023 deliveries", value: 181, unit: "万辆", unitEn: "k" },
      { label: "超充桩", labelEn: "Superchargers", value: 6, unit: "万个", unitEn: "k" },
      { label: "全球员工", labelEn: "Global staff", value: 14, unit: "万人", unitEn: "k" },
    ],
    timeline: [
      { year: "2003", title: "公司成立", titleEn: "Founded", desc: "工程师团队创办特斯拉", descEn: "An engineering team starts Tesla" },
      { year: "2008", title: "Roadster", titleEn: "Roadster", desc: "第一辆电动跑车", descEn: "The first electric sports car" },
      { year: "2012", title: "Model S", titleEn: "Model S", desc: "豪华轿车惊艳市场", descEn: "A luxury sedan stuns the market" },
      { year: "2020", title: "上海工厂", titleEn: "Shanghai factory", desc: "中国制造供应全球", descEn: "Made-in-China supplies the world" },
    ],
  },
  {
    id: "byd",
    name: "比亚迪",
    nameEn: "BYD",
    slug: "byd",
    category: "transport",
    logo: "🔋",
    color: "#E60012",
    slogan: "Build Your Dreams",
    sloganEn: "Build Your Dreams",
    description: "名字是“成就梦想”的缩写，最早是做电池的。",
    descriptionEn: "Its name means 'Build Your Dreams'; it started making batteries.",
    founded: 1995,
    founder: "王传福",
    founderEn: "Wang Chuanfu",
    country: "中国",
    countryEn: "China",
    funFact: "比亚迪名字是“Build Your Dreams”的缩写，最早是做手机电池的，后来才造车。",
    funFactEn: "BYD stands for 'Build Your Dreams'; it started making phone batteries before cars.",
    keyFacts: [
      "1995年做电池起家",
      "自己造电池也造车，成本可控",
      "2023年中国新能源车销量第一",
      "名字=Build Your Dreams",
    ],
    keyFactsEn: [
      "Started making batteries in 1995",
      "Makes both batteries and cars, controlling cost",
      "#1 in China NEV sales in 2023",
      "Name = Build Your Dreams",
    ],
  },
  {
    id: "didi",
    name: "滴滴",
    nameEn: "Didi",
    slug: "didi",
    category: "transport",
    logo: "🚕",
    color: "#FF7E3D",
    slogan: "一路美好出行",
    sloganEn: "Better Journeys",
    description: "一声“滴滴”就能叫到车，名字来自汽车喇叭声。",
    descriptionEn: "Honk 'DiDi' and a car comes — named after a car horn.",
    founded: 2012,
    founder: "程维",
    founderEn: "Cheng Wei",
    country: "中国",
    countryEn: "China",
    funFact: "滴滴名字来自汽车喇叭“滴滴”声，手机一点就能叫到出租车和网约车。",
    funFactEn: "Didi is named after a car horn's 'di-di'; tap your phone and a car comes.",
    keyFacts: [
      "2012年程维创立",
      "网约车+出租车+顺风车",
      "中国最大出行平台",
      "对手曾是Uber中国",
    ],
    keyFactsEn: [
      "Founded by Cheng Wei in 2012",
      "Ride-hailing + taxis + carpooling",
      "China's biggest mobility platform",
      "Its rival was once Uber China",
    ],
  },
  {
    id: "uber",
    name: "Uber",
    nameEn: "Uber",
    slug: "uber",
    category: "transport",
    logo: "🚙",
    color: "#000000",
    slogan: "你的专属司机",
    sloganEn: "Everyone's Private Driver",
    description: "硅谷网约车鼻祖，最早只在旧金山能叫到黑色大车。",
    descriptionEn: "The Silicon Valley rideshare pioneer, first only black cars in San Francisco.",
    founded: 2009,
    founder: "卡兰尼克 / 坎普",
    founderEn: "Kalanick / Camp",
    country: "美国",
    countryEn: "the United States",
    funFact: "Uber名字来自德语“über”意思是“超越”；最早只在旧金山能叫到黑色大车。",
    funFactEn: "Uber comes from German 'über' meaning 'above'; it started with black cars in SF.",
    keyFacts: [
      "2009年在旧金山成立",
      "开创手机叫车模式",
      "业务遍及全球多国",
      "也有外卖Uber Eats",
    ],
    keyFactsEn: [
      "Founded in San Francisco in 2009",
      "Pioneered booking rides by phone",
      "Operates in many countries",
      "Also runs Uber Eats delivery",
    ],
  },

  // ───────────────────────── Other ─────────────────────────
  {
    id: "barbie",
    name: "芭比",
    nameEn: "Barbie",
    slug: "barbie",
    category: "other",
    logo: "💃",
    color: "#E0218A",
    slogan: "你可以成为任何样子",
    sloganEn: "You Can Be Anything",
    description: "1959年诞生的玩偶，告诉女孩“你可以成为任何人”。",
    descriptionEn: "A doll born in 1959 telling girls 'you can be anything'.",
    founded: 1959,
    founder: "露丝·汉德勒（美泰）",
    founderEn: "Ruth Handler (Mattel)",
    country: "美国",
    countryEn: "the United States",
    funFact: "第一代芭比1959年售价3美元，现在收藏款能卖几万美元；她当过200多种职业。",
    funFactEn: "The first Barbie cost $3 in 1959; she's had over 200 careers.",
    keyFacts: [
      "1959年由露丝·汉德勒发明",
      "美泰公司旗下",
      "芭比当过200多种职业",
      "2023年电影大火",
    ],
    keyFactsEn: [
      "Invented by Ruth Handler in 1959",
      "Owned by Mattel",
      "Barbie has had over 200 careers",
      "The 2023 movie was a huge hit",
    ],
  },
  {
    id: "new-oriental",
    name: "新东方",
    nameEn: "New Oriental",
    slug: "new-oriental",
    category: "other",
    logo: "📚",
    color: "#FF6600",
    slogan: "终身学习全球视野",
    sloganEn: "Lifelong Learning",
    description: "最早教人出国考托福的教育品牌，创始人曾是北大老师。",
    descriptionEn: "Started teaching TOEFL for studying abroad; its founder was a Peking University teacher.",
    founded: 1993,
    founder: "俞敏洪",
    founderEn: "Yu Minhong",
    country: "中国",
    countryEn: "China",
    funFact: "新东方最早是教人出国考托福的，创始人俞敏洪曾是北大老师，后来转型做直播带货也火了。",
    funFactEn: "New Oriental started with TOEFL prep; founder Yu Minhong was a PKU teacher.",
    keyFacts: [
      "1993年俞敏洪创立",
      "从出国英语培训起家",
      "后来转型东方甄选直播",
      "中国知名教育品牌",
    ],
    keyFactsEn: [
      "Founded by Yu Minhong in 1993",
      "Started with study-abroad English prep",
      "Later pivoted to livestream shopping",
      "A well-known Chinese education brand",
    ],
  },
  {
    id: "xueersi",
    name: "学而思",
    nameEn: "Xueersi",
    slug: "xueersi",
    category: "other",
    logo: "✏️",
    color: "#00A6FB",
    slogan: "激发兴趣培养习惯",
    sloganEn: "Inspire Interest",
    description: "从一个小数学辅导班做起的在线教育大公司。",
    descriptionEn: "A small math tutoring class that became an online-education giant.",
    founded: 2003,
    founder: "张邦鑫",
    founderEn: "Zhang Bangxin",
    country: "中国",
    countryEn: "China",
    funFact: "学而思最早是一个北大学生办的数学小辅导班，后来变成好未来集团。",
    funFactEn: "Xueersi started as a small math class by a student; it grew into TAL Education Group.",
    keyFacts: [
      "2003年张邦鑫创办",
      "从小数学辅导班做起",
      "母公司好未来（TAL）",
      "专注K12素质教育",
    ],
    keyFactsEn: [
      "Founded by Zhang Bangxin in 2003",
      "Started as a small math tutoring class",
      "Parent company is TAL Education",
      "Focused on K-12 quality education",
    ],
  },
  {
    id: "michelin",
    name: "米其林",
    nameEn: "Michelin",
    slug: "michelin",
    category: "other",
    logo: "🛞",
    color: "#27509B",
    slogan: "更好的移动方式",
    sloganEn: "A Better Way Forward",
    description: "做轮胎的公司出了本指南给餐厅打星，“米其林星级”成了美食最高荣誉。",
    descriptionEn: "A tyre company whose restaurant guide made 'Michelin stars' the top food honour.",
    founded: 1889,
    founder: "米其林兄弟",
    founderEn: "the Michelin brothers",
    country: "法国",
    countryEn: "France",
    funFact: "做轮胎的米其林出了本《米其林指南》给餐厅打星，“米其林星级”成了美食最高荣誉。",
    funFactEn: "Tyre-maker Michelin's restaurant guide made 'Michelin stars' the top food honour.",
    keyFacts: [
      "1889年法国米其林兄弟创立",
      "做轮胎起家",
      "《米其林指南》给餐厅打星",
      "米其林轮胎人是吉祥物",
    ],
    keyFactsEn: [
      "Founded by the Michelin brothers in France in 1889",
      "Started by making tyres",
      "The Michelin Guide awards stars to restaurants",
      "The Michelin Man is its mascot",
    ],
  },
];

// ───────────────────────── helpers ─────────────────────────

export function getAllBrands(): Brand[] {
  return BRANDS;
}

export function getBrandBySlug(slug: string): Brand | undefined {
  return BRANDS.find((b) => b.slug === slug);
}

export function getBrandsByCategory(category: Category | "all"): Brand[] {
  if (category === "all") return BRANDS;
  return BRANDS.filter((b) => b.category === category);
}

export function searchBrands(query: string, limit = 8): Brand[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return BRANDS.filter(
    (b) =>
      b.name.toLowerCase().includes(q) ||
      b.nameEn.toLowerCase().includes(q) ||
      b.slug.includes(q) ||
      b.description.toLowerCase().includes(q),
  ).slice(0, limit);
}

/** related = same category (featured first), fall back to featured brands. */
export function getRelated(slug: string, limit = 4): Brand[] {
  const brand = getBrandBySlug(slug);
  if (!brand) return BRANDS.filter((b) => b.featured).slice(0, limit);
  const sameCat = BRANDS.filter(
    (b) => b.slug !== slug && b.category === brand.category,
  );
  const others = BRANDS.filter(
    (b) => b.slug !== slug && b.category !== brand.category,
  );
  const pool = [
    ...sameCat.sort((a, b) => Number(b.featured) - Number(a.featured)),
    ...others.sort((a, b) => Number(b.featured) - Number(a.featured)),
  ];
  return pool.slice(0, limit);
}
