// BrandPedia Kids — LLM adapter.
// When OPENAI_API_KEY (or a compatible OPENAI_BASE_URL) is set, brand content is
// generated by a real LLM. Otherwise we fall back to the local template generator.
// Either way the result conforms to BrandContent.

import type { BrandContent } from "../types";
import { synthesizeBrand } from "../customBrand";
import { generateContent } from "../contentTemplates";

export interface LLMAdapter {
  available: boolean;
  generateBrandContent(name: string): Promise<BrandContent>;
}

const SYSTEM_PROMPT = `你是 BrandPedia Kids 的内容引擎，为6-14岁儿童写商业科普。
输出严格的 JSON，符合 BrandContent schema：brand(含name/nameEn/slug/category/logo/color/slogan/sloganEn/description/descriptionEn/founded/founder/country/funFact/funFactEn/keyFacts/generated)、
sections(6个维度:brand-story/product-thinking/money-logic/marketing-magic/competition/fun-data，每个含dimension/title/titleEn/content/contentEn/keyPoints)、
script(host1Name/host2Name/segments:[{speaker:'host1'|'host2',text,cardId?}])、
cards([{id,type:'image-text'|'chart'|'quiz'|'timeline',title,payload}])、
quiz([{question,options:[4],correct,explanation,dimension}])、related。
语言：中文为主，附简短英文摘要。语气童趣、短句、多类比。只输出JSON。`;

function envConfig() {
  const apiKey = process.env.OPENAI_API_KEY;
  const baseUrl = (process.env.OPENAI_BASE_URL ?? "https://api.openai.com/v1").replace(/\/$/, "");
  const model = process.env.OPENAI_MODEL ?? "gpt-4o-mini";
  return { apiKey, baseUrl, model };
}

/** Real LLM call → parse JSON → BrandContent. Throws on any failure. */
async function generateWithLLM(name: string): Promise<BrandContent> {
  const { apiKey, baseUrl, model } = envConfig();
  if (!apiKey) throw new Error("no OPENAI_API_KEY");

  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: `请为品牌"${name}"生成完整的儿童科普内容。` },
      ],
      temperature: 0.8,
      response_format: { type: "json_object" },
    }),
  });
  if (!res.ok) throw new Error(`LLM ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const text: string = data.choices?.[0]?.message?.content ?? "";
  const parsed = JSON.parse(text) as BrandContent;
  // ensure the brand is flagged generated and has a slug
  parsed.brand = { ...parsed.brand, generated: true };
  if (!parsed.brand.slug) parsed.brand.slug = parsed.brand.id || slugifyName(name);
  return parsed;
}

function slugifyName(name: string): string {
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `b${name.length}`;
}

/** Local fallback: synthesize metadata + template generator. */
function generateLocal(name: string): BrandContent {
  const brand = synthesizeBrand(name);
  return generateContent(brand);
}

export class RealLLMAdapter implements LLMAdapter {
  available = true;
  async generateBrandContent(name: string): Promise<BrandContent> {
    try {
      return await generateWithLLM(name);
    } catch (err) {
      console.warn("[llm] real generation failed, falling back to local:", err);
      return generateLocal(name);
    }
  }
}

export class LocalLLMAdapter implements LLMAdapter {
  available = false;
  async generateBrandContent(name: string): Promise<BrandContent> {
    return generateLocal(name);
  }
}

let cached: LLMAdapter | null = null;
export function getLLM(): LLMAdapter {
  if (cached) return cached;
  cached = envConfig().apiKey ? new RealLLMAdapter() : new LocalLLMAdapter();
  return cached;
}

/** Top-level helper used by the generate API route. */
export async function generateBrandContent(name: string): Promise<BrandContent> {
  return getLLM().generateBrandContent(name);
}
